### ISSUE TITLE
Plugin template link broken

### ISSUE THREAD

**Issue by pekka-28** [CrypToolProject/CrypTool-2#14]
I have tried to open [CrypTool 2 Plugin.zip](https://www.cryptool.org/assets/ct2/CrypTool%202%20Plugin.zip) on the [Developer HowTo](https://github.com/CrypToolProject/CrypTool-2/wiki/Developer-HowTo) page and get a broken link. The archive is also not available in the Internet Archive and the template it contains is not installed as part of the repository cloning process.

Please advise where I can locate this, or directions on how to rebuild it.

I would like to explore building a few components and don't wish problems in using a non-standard way to create them.

**Comment by n1k0m0** [comment]
we update the description on how to install the template. please read and follow: https://github.com/CrypToolProject/CrypTool-2/tree/main/documentation/CrypPluginTemplate

**Comment by n1k0m0** [comment]
we update the description on how to install the template. please read and follow: https://github.com/CrypToolProject/CrypTool-2/tree/main/documentation/CrypPluginTemplate
