### ISSUE TITLE
Not able to save or open files

### ISSUE THREAD

**Issue by Srivignesh31** [CrypToolProject/CrypTool-2#2]
Machine SPEC - Mac with M1 chip 
Using parallel desktop - 17.1.1 - Windows 11

<img width="605" alt="image" src="https://user-images.githubusercontent.com/44160548/149627421-3b7d7c81-77bb-4bcb-a23f-308dc0e3d781.png">

**Comment by CrypToolProject** [comment]
Sorry, there is no Windows 11 support yet planned. Please test/use with Windows 10 on another machine.
